# Modified by Aslan Satary Dizaji, Copyright (c) 2022.

# Copyright (c) 2021, salesforce.com, inc.
# All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
# For full license text, see the LICENSE file in the repo root
# or https://opensource.org/licenses/BSD-3-Clause

env:
  - scenario_name: uniform_scenario_for_vote_and_invest
  - components:
    - Build:
      - payment: 10
      - payment_max_skill_multiplier: np.array([5, 5, 5])
      - skill_dist: pareto
      - build_labor: 10
    - ContinuousDoubleAuction:
      - max_bid_ask: 10
      - order_labor: 0.25
      - order_duration: 50
      - max_num_orders: 5
    - Gather:
      - move_labor: 1
      - collect_labor: 1
      - skill_dist: none   
    - PlannerVotesPlannerInvestsResources:
      - disable_taxes: False
      - tax_model: model_wrapper
      - period: 100
      - rate_min: 0.0
      - rate_max: 1.0
      - rate_disc: 0.05
      - n_brackets: 7
      - top_bracket_cutoff: 100
      - usd_scaling: 1000.0
      - bracket_spacing: us-federal
      - fixed_bracket_rates: None
      - pareto_weight_type:  inverse_income
      - saez_fixed_elas: None
      - tax_annealing_schedule:
      - -100
      - 0.001
  - n_agents: 5
  - world_size: 
  - 42
  - 42
  - episode_length: 2000
  - multi_action_mode_agents: False                                                 
  - multi_action_mode_planner: True   
  - flatten_observations: True
  - flatten_masks: True 
  - allow_observation_scaling: True
  - dense_log_frequency: 20
  - world_dense_log_frequency: 50
  - collate_agent_step_and_reset_data: False
  - seed: None    
  - planner_gets_spatial_info: True
  - full_observability: False
  - mobile_agent_observation_range: 5
  - starting_wood_coverage: 0.05
  - wood_regen_halfwidth: 0.5
  - wood_regen_weight: 0.05
  - wood_max_health: 1
  - wood_clumpiness: 0.25
  - starting_stone_coverage: 0.05
  - stone_regen_halfwidth: 0.5
  - stone_regen_weight: 0.05
  - stone_max_health: 1
  - stone_clumpiness: 0.25
  - starting_iron_coverage: 0.05
  - iron_regen_halfwidth: 0.5
  - iron_regen_weight: 0.05
  - iron_max_health: 1
  - iron_clumpiness: 0.25
  - gradient_steepness: 1
  - checker_source_blocks: False
  - starting_agent_coin: 50
  - isoelastic_eta: 0.23
  - energy_cost: 0.21
  - energy_warmup_constant: 0
  - energy_warmup_method: 'decay'
  - planner_reward_type: 'coin_maximin_times_productivity'
  - mixing_weight_gini_vs_coin:  0.0
  - mixing_weight_maximin_vs_coin: 0.0
general:
  ckpt_frequency_steps: 2000
  cpus: 5
  episodes: 15
  gpus: 0
  restore_tf_weights_agents: phase1/ckpts/agent.tf.weights.global-step-10000 # path to phase 1 agent policy checkpoint
  restore_tf_weights_planner: ''
  train_planner: true
agent_policy:
  clip_param: 0.3
  entropy_coeff: 0.025
  entropy_coeff_schedule: null
  gamma: 0.998
  grad_clip: 10.0
  kl_coeff: 0.0
  kl_target: 0.01
  lambda: 0.98
  lr: 0.0003
  lr_schedule: null
  model:
    custom_model: keras_conv_lstm
    custom_model_config:
      fc_dim: 128
      idx_emb_dim: 4
      input_emb_vocab: 100
      lstm_cell_size: 128
      num_conv: 2
      num_fc: 2
    max_seq_len: 25
  use_gae: true
  vf_clip_param: 50.0
  vf_loss_coeff: 0.05
  vf_share_layers: false
planner_policy:
  clip_param: 0.3
  entropy_coeff: 0.125
  entropy_coeff_schedule:
  - - 0
    - 2.0
  - - 50000000
    - 0.125
  gamma: 0.998
  grad_clip: 10.0
  kl_coeff: 0.0
  kl_target: 0.01
  lambda: 0.98
  lr: 0.0001
  lr_schedule: null
  model:
    custom_model: keras_conv_lstm
    custom_model_config:
      fc_dim: 256
      idx_emb_dim: 4
      input_emb_vocab: 100
      lstm_cell_size: 256
      num_conv: 2
      num_fc: 2
    max_seq_len: 25
  use_gae: true
  vf_clip_param: 50.0
  vf_loss_coeff: 0.05
  vf_share_layers: false
trainer:
  batch_mode: truncate_episodes
  env_config: null
  local_tf_session_args:
    inter_op_parallelism_threads: 2
    intra_op_parallelism_threads: 24
  metrics_smoothing_episodes: null
  multiagent: null
  no_done_at_end: false
  num_envs_per_worker: 1
  num_gpus: 0
  num_gpus_per_worker: 0
  num_sgd_iter: 1
  num_workers: 5
  observation_filter: NoFilter
  rollout_fragment_length: 200
  seed: null
  sgd_minibatch_size: 1500
  shuffle_sequences: true
  tf_session_args:
    allow_soft_placement: true
    device_count:
      CPU: 5
      GPU: 0
    gpu_options:
      allow_growth: true
    inter_op_parallelism_threads: 2
    intra_op_parallelism_threads: 24
    log_device_placement: false
  train_batch_size: 6000